function Answer = bathyrange(n,s,e,w)

    %set up main window figure
    dialogWind = figure('Units', 'characters', ...
            'Position', [110 25 35 10], ...
            'MenuBar', 'none', ...
            'NumberTitle', 'off', ...
            'Name', 'Choose Bathymetry') ;
    centerpanel = uipanel('bordertype', 'etchedin', ...
            'Units', 'normalized', ...
            'Position', [0 0 1 1], ...
            'Parent', dialogWind) ;
            
    north = uicontrol('Style', 'edit', ...
            'Units', 'characters', ...
            'String', num2str(n), ...
            'Position', [13.8 7 7 1], ...
            'HorizontalAlignment', 'center', ...
            'BackgroundColor', 'white', ...
            'Parent', centerpanel) ;
    north_label = uicontrol('Style', 'text', ...
            'Units', 'characters', ...
            'String', 'North', ...
            'Position', [13.5 8 7 1], ...
            'HorizontalAlignment', 'center', ...
            'Parent', centerpanel) ;
    south = uicontrol('Style', 'edit',...
            'Units', 'characters', ...
            'String', num2str(s), ...
            'Position', [13.8 4 7 1], ...
            'HorizontalAlignment', 'center', ...
            'BackgroundColor', 'white', ...
            'Parent', centerpanel) ;
    south_label = uicontrol('Style', 'text', ...
            'Units', 'characters', ...
            'String', 'South', ...
            'Position', [13.7 2.7 7 1], ...
            'HorizontalAlignment', 'center', ....
            'Parent', centerpanel) ;
    east = uicontrol('style', 'edit', ...
            'Units', 'characters', ...
            'String', num2str(e), ...
            'Position', [24.4 5.5 7 1], ...
            'HorizontalAlignment', 'center', ...
            'BackgroundColor', 'white', ...
            'Parent', centerpanel) ;
    east_label = uicontrol('Style', 'text', ...
            'Units', 'characters', ...
            'String', 'East', ...
            'Position', [24.4 6.5 7 1], ...
            'HorizontalAlignment', 'center', ...
            'Parent', centerpanel) ;
    west = uicontrol('style', 'edit', ...
            'Units', 'characters', ...
            'String', num2str(w), ...
            'Position', [3 5.5 7 1], ...
            'HorizontalAlignment', 'center', ...
            'BackgroundColor', 'white', ...
            'Parent', centerpanel) ;
    west_label = uicontrol('Style', 'text', ...
            'Units', 'characters', ...
            'String', 'West', ...
            'Position', [3 6.5 7 1], ...
            'HorizontalAlignment', 'center', ...
            'Parent', centerpanel) ;
        
    okayButton = uicontrol('Style', 'pushbutton', ...
            'Units', 'normalized', ...
            'Position', [.13,.1,.2,.15], ...
            'String', 'OK', ...
            'Parent', centerpanel, ...
            'callback', @okCallback) ;
    cancelButton = uicontrol('Style', 'pushbutton', ...
            'Units', 'normalized', ...
            'Position', [.73,.1,.2,.15], ...
            'String', 'Cancel', ...
            'Parent', centerpanel, ...
            'Callback', @cancCallback) ;

    %initialize ANSWER to empty cell array
    Answer = 1:4;

    %wait for user input, and close once a button is pressed 
    uiwait(dialogWind);

    %callbacks for 'OK' and 'Cancel' buttons
    function okCallback(hObject,eventdata)
        Answer(1) = str2double(get(north,{'String'}));
        Answer(2) = str2double(get(south,{'String'}));
        Answer(3) = str2double(get(east,{'String'}));
        Answer(4) = str2double(get(west,{'String'}));
        uiresume(dialogWind);
        close(dialogWind);
    end

    function cancCallback(hObject,eventdata)
        Answer = [] ;
        uiresume(dialogWind);
        close(dialogWind);
    end

end