# Makefile for USML propagation model: Propagation Loss and Reverberation Model

include ../../Symbols.mk
include ../../Common.mk

all: \
	refraction_test.o \
	reflection_test.o \
	proploss_test.o \
	eigenray_test.o \

