%% plot_wavefront
% Plot the wavefront generated by WaveQ3D model.  Used as a debugging
% tool during scenario development.
%
% clear ; 
close all
deg2km = ( 1852.0 * 60.0 ) / 1e3 ;

% wavefront = load_wavefront( 'simple_wedge_wavefront.nc' ) ;%
t_index = find( wavefront.travel_time <= 1.500001 ) ;
k = 1:10:length(t_index);

%% plot vertical slice through wavefront at AZ=135 launch angle

[p,az_index] = min(abs( wavefront.source_az - 135.0 ) ) ;
inc_de = wavefront.source_de(2) - wavefront.source_de(1) ;
de_index = [] ;
for de = 0:-5:-60;
    [p,m] = min(abs( wavefront.source_de - de )) ;
    de_index = [ de_index m ] ;
end

wlat = squeeze(wavefront.latitude(t_index,de_index,az_index)) * deg2km ;
wlng = squeeze(wavefront.longitude(t_index,de_index,az_index)) * deg2km ;
walt = squeeze(wavefront.altitude(t_index,de_index,az_index))  ;

xtarget  = 0.01:0.01:2.5 ;
ytarget = zeros(size(xtarget)) ;
ztarget = -100.0 * ones(size(xtarget)) ;

figure;
h = plot3( wlng, wlat, walt, 'k-', ...
       wlng(k,:)', wlat(k,:)', walt(k,:)', 'k:') ;
xlabel('Cross Slope Range (km)');
ylabel('Down Slope Range (km)');
zlabel('Depth (m)');
title('135^o AZ');

view(0,90);

set(gca,'XLim',[0 2.5]);
set(gca,'YLim',[-0.5 1.5]);
entries = [ h(1) h(1+length(de_index)) ] ;
legend(entries,'ray paths','wavefronts','Location','NorthEast');

%% plot horizontal slice through wavefront at DE=-10 launch angle

[p,de_index] = min(abs( wavefront.source_de + 10.0 ) ) ;
az_index = [] ;
for az = wavefront.source_az(1):5:wavefront.source_az(end);
    [p,m] = min(abs( wavefront.source_az - az )) ;
    az_index = [ az_index m ] ;
end

wlat = squeeze(wavefront.latitude(t_index,de_index,az_index)) * deg2km ;
wlng = squeeze(wavefront.longitude(t_index,de_index,az_index)) * deg2km ;
walt = squeeze(wavefront.altitude(t_index,de_index,az_index))  ;
       
figure;
h = plot3( wlng, wlat, walt, 'k-', ...
       wlng(k,:)', wlat(k,:)', walt(k,:)', 'k:');
xlabel('Cross Slope Range (km)');
ylabel('Down Slope Range (km)');
zlabel('Depth (m)');
title('-10^o D/E');
view(0,90);

set(gca,'XLim',[0 2.5]);
set(gca,'YLim',[-0.5 1.5]);
entries = [ h(1) h(1+length(az_index)) ] ;
legend(entries,'ray paths','wavefronts','Location','NorthEast');

